import { createAction, props } from '@ngrx/store';
import { Card } from 'src/app/model/card.model';
import { List } from 'src/app/model/list.model';

export const LoadBoard = createAction('[Board] Load Board', props<{ name: string }>());
export const BoardLoaded = createAction('[Board] Board Loaded', props<{ id: string, lists: List[], cards: Card[] }>());
export const CreateList = createAction('[Board] Create List', props<{ name: string }>());
export const ListCreated = createAction('[Board] List Created', props<{ list: List }>());
export const ArchiveList = createAction('[Board] Archive List', props<{ id: string }>());
export const ListArchived = createAction('[Board] List Archived', props<{ id: string }>());
export const ListUpdated = createAction('[Board] List Updated', props<{ list: List }>());
export const RenameList = createAction('[Board] Rename List', props<{ name: string, list: List }>());
export const ToggleSubscribedList = createAction('[Board] Toggle Subscribed List', props<{ list: List }>());
export const MoveList = createAction('[Board] Move List', props<{ list: List, newIndex: number }>());
export const CopyList = createAction('[Board] Copy List', props<{ list: List, name: string }>());
export const CreateCard = createAction('[Board] Create Card', props<{ name: string, idList: string, pos: number }>());
export const CardCreated = createAction('[Board] Card Created', props<{ card: Card }>());
export const DeleteCard = createAction('[Board] Delete Card', props<{ id: string }>());
export const CardDeleted = createAction('[Board] Card Deleted', props<{ id: string }>());
export const UpdateCard = createAction('[Board] Update Card', props<{ card: Card }>());
export const CardUpdated = createAction('[Board] Card Updated', props<{ card: Card }>());
export const CopyCard = createAction('[Board] Copy Card', props<{ card: Card, name: string, idList: string, index: number }>());
export const MoveCard = createAction('[Board] Move Card', props<{ card: Card, idList: string, index: number }>());
export const ArchiveAllCards = createAction('[Board] Archive All Cards', props<{ idList: string }>());
export const SortCards = createAction('[Board] Sort Cards', props<{ idList: string, sortBy: 'newest' | 'oldest' | 'alphabetically' }>());
export const MoveAllCards = createAction('[Board] Move All Cards', props<{ prev: string, next: string }>());
